name: sdn_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^5.0.11
  github_sign_in_plus: ^0.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
